# Generated by Django 3.2.13 on 2022-07-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('orderID', models.IntegerField(max_length=50)),
                ('totalCost', models.DecimalField(decimal_places=3, max_digits=1000)),
            ],
        ),
    ]
