# Generated by Django 4.0.4 on 2022-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
